### PR TITLE
KeyValue

### PR DESCRIPTION
**Pull request by tpietzsch**
Implements `N5GoogleCloudStorageReader/Writer` via `KeyValueAccess`.

Mock tests all run successfully. I had to add a wrapper for the mock `Storage` used for testing to add bucket handling methods.

Could someone run the real backend tests, @cmhulbert, @bogovicj? I don't have GCS set up...

I the mock tests, I get a lot of these warnings:
```
Jun 20, 2023 11:23:53 AM com.google.api.client.googleapis.services.AbstractGoogleClient <init>
WARNING: Application name is not set. Call Builder#setApplicationName.
```
I tried hard to find that mysterious `Builder` where I can `setApplicationName`, but no luck... If these warnings happen with the real backend too, I'll have to look harder. Otherwise, maybe we can just leave it like that?

Should we try to remove the `org.janelia.saalfeldlab.googlecloud` package? It looks like this did something with credentials originally, but was depleted of all functionality since then.

### CODE REVIEW

**Comment by bogovicj** [comment]
Thanks @tpietzsch !
I'll have a go at testing.

**Comment by bogovicj** [comment]
27/30 tests pass when run on a real GCS backend.  The three that fail complain about not being able to delete things, 

<details>

<summary> for example: </summary> 
```
com.google.cloud.storage.StorageException: The bucket you tried to delete is not empty.
	at com.google.cloud.storage.StorageException.translate(StorageException.java:165)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:297)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.delete(HttpStorageRpc.java:629)
	at com.google.cloud.storage.StorageImpl.lambda$delete$18(StorageImpl.java:480)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.Retrying.run(Retrying.java:60)
	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1476)
	at com.google.cloud.storage.StorageImpl.delete(StorageImpl.java:480)
	at org.janelia.saalfeldlab.n5.googlecloud.GoogleCloudStorageKeyValueAccess.delete(GoogleCloudStorageKeyValueAccess.java:272)
	at org.janelia.saalfeldlab.n5.CachedGsonKeyValueN5Writer.remove(CachedGsonKeyValueN5Writer.java:148)
	at org.janelia.saalfeldlab.n5.N5Writer.remove(N5Writer.java:189)
	at org.janelia.saalfeldlab.n5.AbstractN5Test.testReaderCreation(AbstractN5Test.java:1090)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
DELETE https://storage.googleapis.com/storage/v1/b/n5-test-13341852838635707128-bucket
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The bucket you tried to delete is not empty.",
    "reason" : "conflict"
  } ],
  "message" : "The bucket you tried to delete is not empty."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.delete(HttpStorageRpc.java:625)
	... 39 more

```
<details>

**Comment by tpietzsch** [comment]
> Maybe it's easiest for us to address this since we can test it more easily that you can. What do you think?

That would be nice 👍 

Is it always about the bucket not being empty? Maybe there is a leftover "/" blob or something like that?

**Comment by bogovicj** [comment]
Figured it out!  Can you please merge https://github.com/saalfeldlab/n5-google-cloud/commit/49dd56ecb439da5c23369520a008ef244f690472 onto your keyvalue branch so it appears in this PR?

Summary: we were using a some objects under the root were not being deleted (e.g. attributes.json) turns out we need a `""` prefix instead of `"/"`.  Also, GCS needs the bucket to be empty before removing, so we'll always need to delete *everything* before deleting a bucket :-/.

For future reference:
https://cloud.google.com/storage/docs/deleting-objects#delete-objects-in-bulk
I also made a[ note in the code.](https://github.com/saalfeldlab/n5-google-cloud/blob/keyvalue/src/main/java/org/janelia/saalfeldlab/n5/googlecloud/GoogleCloudStorageKeyValueAccess.java#L278-L279)

Thanks again @tpietzsch !

**Pull request merged**
